[package]
name = "treeLib"
version = "0.1.0"
authors = ["Akmaljon <ajalilov@velox.biz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antlr-rust = "=0.2.0-dev.2"
[dependencies.uuid]
version = "=0.8.*"